### ISSUE TITLE
Request for training data links - song lyrics

### ISSUE THREAD

**Issue by GenTxt** [vineetjohn/linguistic-style-transfer#57]
Hi:

Thanks for the repo. I am interested in testing  the lyrics generating option and would appreciate links to the files required for "lyrics_adapter.py"

artist-song-line.top30artists.txt
lyrics-val.txt
artist-val.txt
lyrics-test.txt
artist-test.txt
lyrics-train.txt
artist-train.txt
lyrics-all.txt
artist-all.txt

If this is not possible could you please provide an example of the text format required for processing.
I would like to use my own corpus files, for example, Project Gutenberg etexts.

Cheers

**Comment by vineetjohn** [comment]
The lyrics can be sourced from 
https://www.kaggle.com/mousehead/songlyrics

Please ignore the corpus adapters. They are just custom scripts for massaging the data into the required files (lyrics-val.txt, artist-val.txt, lyrics-test.txt, artist-test.txt, lyrics-train.txt, artist-train.txt)

You can parse this data into a file containing lyrics (lyrics-all.txt) and their corresponding artists (artists-all.txt), and later split this main file into the train, validation and test sets.

The format is simple: Both files contain one verse(s)/artist per line, and both files have the same number of lines

| lyrics-all.txt | artists-all.txt |
| --- | --- |
| I've found a real fine woman | Paul McCartney |
| But when you're walking down the street | Gary Numan |
| You could have done better but I don't mind | Bob Dylan |
| Or a crime | Pet Shop Boys |
| Maybe you bought all the lines that she told you | Kris Kristofferson |
| I know a tiny waterfall | Paul McCartney |
| Striking holy terror | Kris Kristofferson |
| They've got stamps of many countries | Joni Mitchell |
| Cash in dime for a ride | Marilyn Manson |
| That's why I chose (that's why I chose) | Ray Charles |
